### ISSUE TITLE
Incorrect db password 

### ISSUE THREAD

**Issue by IWang20** [stevenwang3985/deploycvat#3]
![image](https://github.com/stevenwang3985/deploycvat/assets/67295762/53b5f993-b997-4dac-93cf-b5eb24fb39e9)

**Comment by stevenwang3985** [comment]
Is the port that cvat server listens to incoming request set as 80 or 8080 in the dockerfile ?    But the last error complains about password auth. I have never seen this.  for single user container,  I used to login cvat with the superuser created during installation.  For multi-user,  does each user creats its own account ?
