### ISSUE TITLE
User can't export annotations - permission denied

### ISSUE THREAD

**Issue by IWang20** [stevenwang3985/deploycvat#4]
![image](https://github.com/user-attachments/assets/d8c4a22b-dca6-4172-be64-c4f7c5c7ebe4)

**Comment by stevenwang3985** [comment]
Does wangin-test user has  admin privileges ?

From: Ian W ***@***.***>
Sent: Saturday, July 13, 2024 10:06 PM
To: stevenwang3985/deploycvat ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [stevenwang3985/deploycvat] User can't export annotations - permission denied (Issue #4)


image.png (view on web)<https://github.com/user-attachments/assets/d8c4a22b-dca6-4172-be64-c4f7c5c7ebe4>

**Comment by IWang20** [comment]
Yes, that was the issue, it was because of lack of super user
